version: '2'
services:
    webscrapper-app:
        image: webscrapper
        external_links:
            - webscrapper-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/webscrapper?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    webscrapper-mysql:
        extends:
            file: mysql.yml
            service: webscrapper-mysql
